export const metadata = {
  title: 'Happily Ever After',
  description: 'Generated by Next.js',
}

declare global {
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/ddw6cok.css"></link>
        <script defer src="https://developers.kakao.com/sdk/js/kakao.min.js"></script>
      </head>
      <body>{children}</body>
    </html>
  )
}
